version: "3"

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"
  app:
    env_file:
      - .env.local
    build: .
    environment:
      DB_USER: wiki
      DB_PASSWORD: wiki
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: wiki
    volumes:
      - ".:/go/src"
    ports:
      - "8000:8000"
    tty: true
    links:
      - db
    depends_on:
      - db
    restart: always
  adminer:
    image: adminer
    ports: 
      - "8080:8080"